// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pbdrone {

  /// <summary>Holder for reflection information generated from messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXNzYWdlcy5wcm90bxIHcGJkcm9uZSIfCglIZWFydGJlYXQSEgoKYXJy",
            "aHl0aG1pYRgBIAEoAiLSAgoPSW50ZXJmYWNlU3RhdHVzEjcKD2ludGVyZmFj",
            "ZV9zdGF0ZRgBIAEoDjIeLnBiZHJvbmUuSW50ZXJmYWNlU3RhdHVzLlN0YXRl",
            "EjgKDGZhaWx1cmVfdHlwZRgCIAEoDjIiLnBiZHJvbmUuSW50ZXJmYWNlU3Rh",
            "dHVzLkZhaWxTdGF0ZRIWCg5mYWlsdXJlX291dHB1dBgDIAEoCRITCgthY3Rp",
            "dmVfbW9kZRgEIAEoCCIwCgVTdGF0ZRILCgdPRkZMSU5FEAASDgoKQVRURU1Q",
            "VElORxABEgoKBk9OTElORRACIm0KCUZhaWxTdGF0ZRIOCgpOT19GQUlMVVJF",
            "EAASEwoPQVRURU1QVF9GQUlMVVJFEAESEwoPRFJPUFBFRF9GQUlMVVJFEAIS",
            "EgoOVEhSRUFEX0ZBSUxVUkUQAxISCg5USFJFQURfVElNRU9VVBAEInIKDEZs",
            "aWdodFN0YXR1cxIxCgxmbGlnaHRfc3RhdGUYASABKA4yGy5wYmRyb25lLkZs",
            "aWdodFN0YXR1cy5TdGF0ZSIvCgVTdGF0ZRILCgdTVE9QUEVEEAASDQoJT05f",
            "R1JPVU5EEAESCgoGSU5fQUlSEAIiOgoNQ29udHJvbERldmljZRIRCglhdXRv",
            "X21vZGUYAiABKAgSFgoOcmV0dXJuX3RvX2hvbWUYAyABKAgipQEKCVRlbGVt",
            "ZXRyeRIRCglsb25naXR1ZGUYASABKAESEAoIbGF0aXR1ZGUYAiABKAESEAoI",
            "YWx0aXR1ZGUYAyABKAISEgoKc2F0ZWxsaXRlcxgEIAEoBRINCgV2ZWxfeBgF",
            "IAEoAhINCgV2ZWxfeRgGIAEoAhINCgV2ZWxfehgJIAEoAhIPCgdhY2NlbF94",
            "GAcgASgCEg8KB2FjY2VsX3kYCCABKAIiIAoNRmxpZ2h0QW5vbWFseRIPCgdh",
            "bm9tYWx5GAEgAygJIiwKCEFDRUVycm9yEhEKCXRpbWVzdGFtcBgBIAEoCRIN",
            "CgVlcnJvchgCIAEoCSK9AgoNTWlzc2lvblN0YXR1cxIzCg1taXNzaW9uX3N0",
            "YWdlGAEgASgOMhwucGJkcm9uZS5NaXNzaW9uU3RhdHVzLlN0YWdlEhEKCWFj",
            "dGl2YXRlZBgCIAEoCBITCgtpbl9wcm9ncmVzcxgDIAEoCBIWCg5sYXN0X2xv",
            "bmdpdHVkZRgEIAEoARIVCg1sYXN0X2xhdGl0dWRlGAUgASgBEhUKDWxhc3Rf",
            "YWx0aXR1ZGUYBiABKAISCwoDbG9nGAcgASgJEg4KBmVycm9ycxgIIAEoCCJs",
            "CgVTdGFnZRIRCg1OT1RfQUNUSVZBVEVEEAASCQoFUkVBRFkQARILCgdFTlJP",
            "VVRFEAISDQoJRVhFQ1VUSU5HEAMSDQoJUkVUVVJOSU5HEAQSDAoIT1ZFUlJJ",
            "REUQBRIMCghDT01QTEVURRAGIlIKDU1pc3Npb25Db25maWcSGgoSdHJlYXRt",
            "ZW50X2R1cmF0aW9uGAEgASgFEiUKBnJvdXRlcxgGIAMoCzIVLnBiZHJvbmUu",
            "TWlzc2lvblJvdXRlIkgKD0NvbW1hbmRSZXNwb25zZRIPCgdjb21tYW5kGAEg",
            "ASgJEhIKCnN1Y2Nlc3NmdWwYAiABKAgSEAoIcmVzcG9uc2UYAyABKAkiggEK",
            "CkFyZWFSZXN1bHQSDgoGYXJlYUlEGAEgASgFEioKBnN0YXR1cxgCIAEoDjIa",
            "LnBiZHJvbmUuQXJlYVJlc3VsdC5TdGF0dXMiOAoGU3RhdHVzEg8KC05PVF9T",
            "VEFSVEVEEAASDwoLSU5fUFJPR1JFU1MQARIMCghGSU5JU0hFRBACIjMKDUNv",
            "bmZpZ3VyYXRpb24SIgoEbGlzdBgBIAMoCzIULnBiZHJvbmUuQ29uZmlnRW50",
            "cnkiSQoLQ29uZmlnRW50cnkSDwoHc2VjdGlvbhgBIAEoCRIOCgZvcHRpb24Y",
            "AiABKAkSDQoFdmFsdWUYAyABKAkSCgoCaWQYBCABKAUi2AEKDE1pc3Npb25S",
            "b3V0ZRIPCgdyb3V0ZUlEGAEgASgFEiwKBnN0YXR1cxgCIAEoDjIcLnBiZHJv",
            "bmUuTWlzc2lvblJvdXRlLlN0YXR1cxISCgpmbHlUaHJvdWdoGAMgASgIEh0K",
            "FWxhc3RFbnRyeU1vZGlmaWNhdGlvbhgEIAEoAxIcChRsYXN0QXJlYU1vZGlm",
            "aWNhdGlvbhgFIAEoAyI4CgZTdGF0dXMSDwoLTk9UX1NUQVJURUQQABIPCgtJ",
            "Tl9QUk9HUkVTUxABEgwKCEZJTklTSEVEEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.Heartbeat), global::Pbdrone.Heartbeat.Parser, new[]{ "Arrhythmia" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.InterfaceStatus), global::Pbdrone.InterfaceStatus.Parser, new[]{ "InterfaceState", "FailureType", "FailureOutput", "ActiveMode" }, null, new[]{ typeof(global::Pbdrone.InterfaceStatus.Types.State), typeof(global::Pbdrone.InterfaceStatus.Types.FailState) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.FlightStatus), global::Pbdrone.FlightStatus.Parser, new[]{ "FlightState" }, null, new[]{ typeof(global::Pbdrone.FlightStatus.Types.State) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.ControlDevice), global::Pbdrone.ControlDevice.Parser, new[]{ "AutoMode", "ReturnToHome" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.Telemetry), global::Pbdrone.Telemetry.Parser, new[]{ "Longitude", "Latitude", "Altitude", "Satellites", "VelX", "VelY", "VelZ", "AccelX", "AccelY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.FlightAnomaly), global::Pbdrone.FlightAnomaly.Parser, new[]{ "Anomaly" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.ACEError), global::Pbdrone.ACEError.Parser, new[]{ "Timestamp", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.MissionStatus), global::Pbdrone.MissionStatus.Parser, new[]{ "MissionStage", "Activated", "InProgress", "LastLongitude", "LastLatitude", "LastAltitude", "Log", "Errors" }, null, new[]{ typeof(global::Pbdrone.MissionStatus.Types.Stage) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.MissionConfig), global::Pbdrone.MissionConfig.Parser, new[]{ "TreatmentDuration", "Routes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.CommandResponse), global::Pbdrone.CommandResponse.Parser, new[]{ "Command", "Successful", "Response" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.AreaResult), global::Pbdrone.AreaResult.Parser, new[]{ "AreaID", "Status" }, null, new[]{ typeof(global::Pbdrone.AreaResult.Types.Status) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.Configuration), global::Pbdrone.Configuration.Parser, new[]{ "List" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.ConfigEntry), global::Pbdrone.ConfigEntry.Parser, new[]{ "Section", "Option", "Value", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pbdrone.MissionRoute), global::Pbdrone.MissionRoute.Parser, new[]{ "RouteID", "Status", "FlyThrough", "LastEntryModification", "LastAreaModification" }, null, new[]{ typeof(global::Pbdrone.MissionRoute.Types.Status) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Code 0
  /// </summary>
  public sealed partial class Heartbeat : pb::IMessage<Heartbeat> {
    private static readonly pb::MessageParser<Heartbeat> _parser = new pb::MessageParser<Heartbeat>(() => new Heartbeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Heartbeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat(Heartbeat other) : this() {
      arrhythmia_ = other.arrhythmia_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heartbeat Clone() {
      return new Heartbeat(this);
    }

    /// <summary>Field number for the "arrhythmia" field.</summary>
    public const int ArrhythmiaFieldNumber = 1;
    private float arrhythmia_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Arrhythmia {
      get { return arrhythmia_; }
      set {
        arrhythmia_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Heartbeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Heartbeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Arrhythmia, other.Arrhythmia)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Arrhythmia != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Arrhythmia);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Arrhythmia != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Arrhythmia);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Arrhythmia != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Heartbeat other) {
      if (other == null) {
        return;
      }
      if (other.Arrhythmia != 0F) {
        Arrhythmia = other.Arrhythmia;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Arrhythmia = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 1 - sent by Drone
  /// </summary>
  public sealed partial class InterfaceStatus : pb::IMessage<InterfaceStatus> {
    private static readonly pb::MessageParser<InterfaceStatus> _parser = new pb::MessageParser<InterfaceStatus>(() => new InterfaceStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InterfaceStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterfaceStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterfaceStatus(InterfaceStatus other) : this() {
      interfaceState_ = other.interfaceState_;
      failureType_ = other.failureType_;
      failureOutput_ = other.failureOutput_;
      activeMode_ = other.activeMode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InterfaceStatus Clone() {
      return new InterfaceStatus(this);
    }

    /// <summary>Field number for the "interface_state" field.</summary>
    public const int InterfaceStateFieldNumber = 1;
    private global::Pbdrone.InterfaceStatus.Types.State interfaceState_ = global::Pbdrone.InterfaceStatus.Types.State.Offline;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.InterfaceStatus.Types.State InterfaceState {
      get { return interfaceState_; }
      set {
        interfaceState_ = value;
      }
    }

    /// <summary>Field number for the "failure_type" field.</summary>
    public const int FailureTypeFieldNumber = 2;
    private global::Pbdrone.InterfaceStatus.Types.FailState failureType_ = global::Pbdrone.InterfaceStatus.Types.FailState.NoFailure;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.InterfaceStatus.Types.FailState FailureType {
      get { return failureType_; }
      set {
        failureType_ = value;
      }
    }

    /// <summary>Field number for the "failure_output" field.</summary>
    public const int FailureOutputFieldNumber = 3;
    private string failureOutput_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FailureOutput {
      get { return failureOutput_; }
      set {
        failureOutput_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "active_mode" field.</summary>
    public const int ActiveModeFieldNumber = 4;
    private bool activeMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ActiveMode {
      get { return activeMode_; }
      set {
        activeMode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InterfaceStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InterfaceStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InterfaceState != other.InterfaceState) return false;
      if (FailureType != other.FailureType) return false;
      if (FailureOutput != other.FailureOutput) return false;
      if (ActiveMode != other.ActiveMode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InterfaceState != global::Pbdrone.InterfaceStatus.Types.State.Offline) hash ^= InterfaceState.GetHashCode();
      if (FailureType != global::Pbdrone.InterfaceStatus.Types.FailState.NoFailure) hash ^= FailureType.GetHashCode();
      if (FailureOutput.Length != 0) hash ^= FailureOutput.GetHashCode();
      if (ActiveMode != false) hash ^= ActiveMode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InterfaceState != global::Pbdrone.InterfaceStatus.Types.State.Offline) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InterfaceState);
      }
      if (FailureType != global::Pbdrone.InterfaceStatus.Types.FailState.NoFailure) {
        output.WriteRawTag(16);
        output.WriteEnum((int) FailureType);
      }
      if (FailureOutput.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FailureOutput);
      }
      if (ActiveMode != false) {
        output.WriteRawTag(32);
        output.WriteBool(ActiveMode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InterfaceState != global::Pbdrone.InterfaceStatus.Types.State.Offline) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InterfaceState);
      }
      if (FailureType != global::Pbdrone.InterfaceStatus.Types.FailState.NoFailure) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FailureType);
      }
      if (FailureOutput.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FailureOutput);
      }
      if (ActiveMode != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InterfaceStatus other) {
      if (other == null) {
        return;
      }
      if (other.InterfaceState != global::Pbdrone.InterfaceStatus.Types.State.Offline) {
        InterfaceState = other.InterfaceState;
      }
      if (other.FailureType != global::Pbdrone.InterfaceStatus.Types.FailState.NoFailure) {
        FailureType = other.FailureType;
      }
      if (other.FailureOutput.Length != 0) {
        FailureOutput = other.FailureOutput;
      }
      if (other.ActiveMode != false) {
        ActiveMode = other.ActiveMode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InterfaceState = (global::Pbdrone.InterfaceStatus.Types.State) input.ReadEnum();
            break;
          }
          case 16: {
            FailureType = (global::Pbdrone.InterfaceStatus.Types.FailState) input.ReadEnum();
            break;
          }
          case 26: {
            FailureOutput = input.ReadString();
            break;
          }
          case 32: {
            ActiveMode = input.ReadBool();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the InterfaceStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("OFFLINE")] Offline = 0,
        [pbr::OriginalName("ATTEMPTING")] Attempting = 1,
        [pbr::OriginalName("ONLINE")] Online = 2,
      }

      public enum FailState {
        [pbr::OriginalName("NO_FAILURE")] NoFailure = 0,
        [pbr::OriginalName("ATTEMPT_FAILURE")] AttemptFailure = 1,
        [pbr::OriginalName("DROPPED_FAILURE")] DroppedFailure = 2,
        [pbr::OriginalName("THREAD_FAILURE")] ThreadFailure = 3,
        [pbr::OriginalName("THREAD_TIMEOUT")] ThreadTimeout = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// Code 2 - sent by Drone
  /// </summary>
  public sealed partial class FlightStatus : pb::IMessage<FlightStatus> {
    private static readonly pb::MessageParser<FlightStatus> _parser = new pb::MessageParser<FlightStatus>(() => new FlightStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FlightStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightStatus(FlightStatus other) : this() {
      flightState_ = other.flightState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightStatus Clone() {
      return new FlightStatus(this);
    }

    /// <summary>Field number for the "flight_state" field.</summary>
    public const int FlightStateFieldNumber = 1;
    private global::Pbdrone.FlightStatus.Types.State flightState_ = global::Pbdrone.FlightStatus.Types.State.Stopped;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.FlightStatus.Types.State FlightState {
      get { return flightState_; }
      set {
        flightState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FlightStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FlightStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FlightState != other.FlightState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FlightState != global::Pbdrone.FlightStatus.Types.State.Stopped) hash ^= FlightState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FlightState != global::Pbdrone.FlightStatus.Types.State.Stopped) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FlightState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FlightState != global::Pbdrone.FlightStatus.Types.State.Stopped) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FlightState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FlightStatus other) {
      if (other == null) {
        return;
      }
      if (other.FlightState != global::Pbdrone.FlightStatus.Types.State.Stopped) {
        FlightState = other.FlightState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FlightState = (global::Pbdrone.FlightStatus.Types.State) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FlightStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("STOPPED")] Stopped = 0,
        [pbr::OriginalName("ON_GROUND")] OnGround = 1,
        [pbr::OriginalName("IN_AIR")] InAir = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// Code 3 - sent by Drone
  /// </summary>
  public sealed partial class ControlDevice : pb::IMessage<ControlDevice> {
    private static readonly pb::MessageParser<ControlDevice> _parser = new pb::MessageParser<ControlDevice>(() => new ControlDevice());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ControlDevice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ControlDevice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ControlDevice(ControlDevice other) : this() {
      autoMode_ = other.autoMode_;
      returnToHome_ = other.returnToHome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ControlDevice Clone() {
      return new ControlDevice(this);
    }

    /// <summary>Field number for the "auto_mode" field.</summary>
    public const int AutoModeFieldNumber = 2;
    private bool autoMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AutoMode {
      get { return autoMode_; }
      set {
        autoMode_ = value;
      }
    }

    /// <summary>Field number for the "return_to_home" field.</summary>
    public const int ReturnToHomeFieldNumber = 3;
    private bool returnToHome_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ReturnToHome {
      get { return returnToHome_; }
      set {
        returnToHome_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ControlDevice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ControlDevice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutoMode != other.AutoMode) return false;
      if (ReturnToHome != other.ReturnToHome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AutoMode != false) hash ^= AutoMode.GetHashCode();
      if (ReturnToHome != false) hash ^= ReturnToHome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutoMode != false) {
        output.WriteRawTag(16);
        output.WriteBool(AutoMode);
      }
      if (ReturnToHome != false) {
        output.WriteRawTag(24);
        output.WriteBool(ReturnToHome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutoMode != false) {
        size += 1 + 1;
      }
      if (ReturnToHome != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ControlDevice other) {
      if (other == null) {
        return;
      }
      if (other.AutoMode != false) {
        AutoMode = other.AutoMode;
      }
      if (other.ReturnToHome != false) {
        ReturnToHome = other.ReturnToHome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            AutoMode = input.ReadBool();
            break;
          }
          case 24: {
            ReturnToHome = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 4 - sent by Drone
  /// </summary>
  public sealed partial class Telemetry : pb::IMessage<Telemetry> {
    private static readonly pb::MessageParser<Telemetry> _parser = new pb::MessageParser<Telemetry>(() => new Telemetry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Telemetry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Telemetry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Telemetry(Telemetry other) : this() {
      longitude_ = other.longitude_;
      latitude_ = other.latitude_;
      altitude_ = other.altitude_;
      satellites_ = other.satellites_;
      velX_ = other.velX_;
      velY_ = other.velY_;
      velZ_ = other.velZ_;
      accelX_ = other.accelX_;
      accelY_ = other.accelY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Telemetry Clone() {
      return new Telemetry(this);
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 1;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 2;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "altitude" field.</summary>
    public const int AltitudeFieldNumber = 3;
    private float altitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Altitude {
      get { return altitude_; }
      set {
        altitude_ = value;
      }
    }

    /// <summary>Field number for the "satellites" field.</summary>
    public const int SatellitesFieldNumber = 4;
    private int satellites_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Satellites {
      get { return satellites_; }
      set {
        satellites_ = value;
      }
    }

    /// <summary>Field number for the "vel_x" field.</summary>
    public const int VelXFieldNumber = 5;
    private float velX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float VelX {
      get { return velX_; }
      set {
        velX_ = value;
      }
    }

    /// <summary>Field number for the "vel_y" field.</summary>
    public const int VelYFieldNumber = 6;
    private float velY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float VelY {
      get { return velY_; }
      set {
        velY_ = value;
      }
    }

    /// <summary>Field number for the "vel_z" field.</summary>
    public const int VelZFieldNumber = 9;
    private float velZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float VelZ {
      get { return velZ_; }
      set {
        velZ_ = value;
      }
    }

    /// <summary>Field number for the "accel_x" field.</summary>
    public const int AccelXFieldNumber = 7;
    private float accelX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float AccelX {
      get { return accelX_; }
      set {
        accelX_ = value;
      }
    }

    /// <summary>Field number for the "accel_y" field.</summary>
    public const int AccelYFieldNumber = 8;
    private float accelY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float AccelY {
      get { return accelY_; }
      set {
        accelY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Telemetry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Telemetry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Altitude, other.Altitude)) return false;
      if (Satellites != other.Satellites) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelX, other.VelX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelY, other.VelY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelZ, other.VelZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AccelX, other.AccelX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AccelY, other.AccelY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Altitude != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Altitude);
      if (Satellites != 0) hash ^= Satellites.GetHashCode();
      if (VelX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelX);
      if (VelY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelY);
      if (VelZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelZ);
      if (AccelX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AccelX);
      if (AccelY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AccelY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Longitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Longitude);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Latitude);
      }
      if (Altitude != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Altitude);
      }
      if (Satellites != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Satellites);
      }
      if (VelX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(VelX);
      }
      if (VelY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(VelY);
      }
      if (AccelX != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(AccelX);
      }
      if (AccelY != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(AccelY);
      }
      if (VelZ != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(VelZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Altitude != 0F) {
        size += 1 + 4;
      }
      if (Satellites != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Satellites);
      }
      if (VelX != 0F) {
        size += 1 + 4;
      }
      if (VelY != 0F) {
        size += 1 + 4;
      }
      if (VelZ != 0F) {
        size += 1 + 4;
      }
      if (AccelX != 0F) {
        size += 1 + 4;
      }
      if (AccelY != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Telemetry other) {
      if (other == null) {
        return;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Altitude != 0F) {
        Altitude = other.Altitude;
      }
      if (other.Satellites != 0) {
        Satellites = other.Satellites;
      }
      if (other.VelX != 0F) {
        VelX = other.VelX;
      }
      if (other.VelY != 0F) {
        VelY = other.VelY;
      }
      if (other.VelZ != 0F) {
        VelZ = other.VelZ;
      }
      if (other.AccelX != 0F) {
        AccelX = other.AccelX;
      }
      if (other.AccelY != 0F) {
        AccelY = other.AccelY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Longitude = input.ReadDouble();
            break;
          }
          case 17: {
            Latitude = input.ReadDouble();
            break;
          }
          case 29: {
            Altitude = input.ReadFloat();
            break;
          }
          case 32: {
            Satellites = input.ReadInt32();
            break;
          }
          case 45: {
            VelX = input.ReadFloat();
            break;
          }
          case 53: {
            VelY = input.ReadFloat();
            break;
          }
          case 61: {
            AccelX = input.ReadFloat();
            break;
          }
          case 69: {
            AccelY = input.ReadFloat();
            break;
          }
          case 77: {
            VelZ = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 5
  /// </summary>
  public sealed partial class FlightAnomaly : pb::IMessage<FlightAnomaly> {
    private static readonly pb::MessageParser<FlightAnomaly> _parser = new pb::MessageParser<FlightAnomaly>(() => new FlightAnomaly());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FlightAnomaly> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightAnomaly() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightAnomaly(FlightAnomaly other) : this() {
      anomaly_ = other.anomaly_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlightAnomaly Clone() {
      return new FlightAnomaly(this);
    }

    /// <summary>Field number for the "anomaly" field.</summary>
    public const int AnomalyFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_anomaly_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> anomaly_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Anomaly {
      get { return anomaly_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FlightAnomaly);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FlightAnomaly other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!anomaly_.Equals(other.anomaly_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= anomaly_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      anomaly_.WriteTo(output, _repeated_anomaly_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += anomaly_.CalculateSize(_repeated_anomaly_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FlightAnomaly other) {
      if (other == null) {
        return;
      }
      anomaly_.Add(other.anomaly_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            anomaly_.AddEntriesFrom(input, _repeated_anomaly_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 6
  /// </summary>
  public sealed partial class ACEError : pb::IMessage<ACEError> {
    private static readonly pb::MessageParser<ACEError> _parser = new pb::MessageParser<ACEError>(() => new ACEError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ACEError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ACEError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ACEError(ACEError other) : this() {
      timestamp_ = other.timestamp_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ACEError Clone() {
      return new ACEError(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private string timestamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ACEError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ACEError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Timestamp);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ACEError other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Timestamp = input.ReadString();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 7
  /// </summary>
  public sealed partial class MissionStatus : pb::IMessage<MissionStatus> {
    private static readonly pb::MessageParser<MissionStatus> _parser = new pb::MessageParser<MissionStatus>(() => new MissionStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionStatus(MissionStatus other) : this() {
      missionStage_ = other.missionStage_;
      activated_ = other.activated_;
      inProgress_ = other.inProgress_;
      lastLongitude_ = other.lastLongitude_;
      lastLatitude_ = other.lastLatitude_;
      lastAltitude_ = other.lastAltitude_;
      log_ = other.log_;
      errors_ = other.errors_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionStatus Clone() {
      return new MissionStatus(this);
    }

    /// <summary>Field number for the "mission_stage" field.</summary>
    public const int MissionStageFieldNumber = 1;
    private global::Pbdrone.MissionStatus.Types.Stage missionStage_ = global::Pbdrone.MissionStatus.Types.Stage.NotActivated;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.MissionStatus.Types.Stage MissionStage {
      get { return missionStage_; }
      set {
        missionStage_ = value;
      }
    }

    /// <summary>Field number for the "activated" field.</summary>
    public const int ActivatedFieldNumber = 2;
    private bool activated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Activated {
      get { return activated_; }
      set {
        activated_ = value;
      }
    }

    /// <summary>Field number for the "in_progress" field.</summary>
    public const int InProgressFieldNumber = 3;
    private bool inProgress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool InProgress {
      get { return inProgress_; }
      set {
        inProgress_ = value;
      }
    }

    /// <summary>Field number for the "last_longitude" field.</summary>
    public const int LastLongitudeFieldNumber = 4;
    private double lastLongitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double LastLongitude {
      get { return lastLongitude_; }
      set {
        lastLongitude_ = value;
      }
    }

    /// <summary>Field number for the "last_latitude" field.</summary>
    public const int LastLatitudeFieldNumber = 5;
    private double lastLatitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double LastLatitude {
      get { return lastLatitude_; }
      set {
        lastLatitude_ = value;
      }
    }

    /// <summary>Field number for the "last_altitude" field.</summary>
    public const int LastAltitudeFieldNumber = 6;
    private float lastAltitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float LastAltitude {
      get { return lastAltitude_; }
      set {
        lastAltitude_ = value;
      }
    }

    /// <summary>Field number for the "log" field.</summary>
    public const int LogFieldNumber = 7;
    private string log_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Log {
      get { return log_; }
      set {
        log_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errors" field.</summary>
    public const int ErrorsFieldNumber = 8;
    private bool errors_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Errors {
      get { return errors_; }
      set {
        errors_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MissionStage != other.MissionStage) return false;
      if (Activated != other.Activated) return false;
      if (InProgress != other.InProgress) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastLongitude, other.LastLongitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastLatitude, other.LastLatitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LastAltitude, other.LastAltitude)) return false;
      if (Log != other.Log) return false;
      if (Errors != other.Errors) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MissionStage != global::Pbdrone.MissionStatus.Types.Stage.NotActivated) hash ^= MissionStage.GetHashCode();
      if (Activated != false) hash ^= Activated.GetHashCode();
      if (InProgress != false) hash ^= InProgress.GetHashCode();
      if (LastLongitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastLongitude);
      if (LastLatitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastLatitude);
      if (LastAltitude != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LastAltitude);
      if (Log.Length != 0) hash ^= Log.GetHashCode();
      if (Errors != false) hash ^= Errors.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MissionStage != global::Pbdrone.MissionStatus.Types.Stage.NotActivated) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MissionStage);
      }
      if (Activated != false) {
        output.WriteRawTag(16);
        output.WriteBool(Activated);
      }
      if (InProgress != false) {
        output.WriteRawTag(24);
        output.WriteBool(InProgress);
      }
      if (LastLongitude != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(LastLongitude);
      }
      if (LastLatitude != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(LastLatitude);
      }
      if (LastAltitude != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(LastAltitude);
      }
      if (Log.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Log);
      }
      if (Errors != false) {
        output.WriteRawTag(64);
        output.WriteBool(Errors);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MissionStage != global::Pbdrone.MissionStatus.Types.Stage.NotActivated) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MissionStage);
      }
      if (Activated != false) {
        size += 1 + 1;
      }
      if (InProgress != false) {
        size += 1 + 1;
      }
      if (LastLongitude != 0D) {
        size += 1 + 8;
      }
      if (LastLatitude != 0D) {
        size += 1 + 8;
      }
      if (LastAltitude != 0F) {
        size += 1 + 4;
      }
      if (Log.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Log);
      }
      if (Errors != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionStatus other) {
      if (other == null) {
        return;
      }
      if (other.MissionStage != global::Pbdrone.MissionStatus.Types.Stage.NotActivated) {
        MissionStage = other.MissionStage;
      }
      if (other.Activated != false) {
        Activated = other.Activated;
      }
      if (other.InProgress != false) {
        InProgress = other.InProgress;
      }
      if (other.LastLongitude != 0D) {
        LastLongitude = other.LastLongitude;
      }
      if (other.LastLatitude != 0D) {
        LastLatitude = other.LastLatitude;
      }
      if (other.LastAltitude != 0F) {
        LastAltitude = other.LastAltitude;
      }
      if (other.Log.Length != 0) {
        Log = other.Log;
      }
      if (other.Errors != false) {
        Errors = other.Errors;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MissionStage = (global::Pbdrone.MissionStatus.Types.Stage) input.ReadEnum();
            break;
          }
          case 16: {
            Activated = input.ReadBool();
            break;
          }
          case 24: {
            InProgress = input.ReadBool();
            break;
          }
          case 33: {
            LastLongitude = input.ReadDouble();
            break;
          }
          case 41: {
            LastLatitude = input.ReadDouble();
            break;
          }
          case 53: {
            LastAltitude = input.ReadFloat();
            break;
          }
          case 58: {
            Log = input.ReadString();
            break;
          }
          case 64: {
            Errors = input.ReadBool();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the MissionStatus message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Stage {
        [pbr::OriginalName("NOT_ACTIVATED")] NotActivated = 0,
        [pbr::OriginalName("READY")] Ready = 1,
        /// <summary>
        /// Stage 2 and 3 are the only times that we receive high-rate telemetry
        /// </summary>
        [pbr::OriginalName("ENROUTE")] Enroute = 2,
        [pbr::OriginalName("EXECUTING")] Executing = 3,
        [pbr::OriginalName("RETURNING")] Returning = 4,
        [pbr::OriginalName("OVERRIDE")] Override = 5,
        [pbr::OriginalName("COMPLETE")] Complete = 6,
      }

    }
    #endregion

  }

  /// <summary>
  /// Code 8
  /// </summary>
  public sealed partial class MissionConfig : pb::IMessage<MissionConfig> {
    private static readonly pb::MessageParser<MissionConfig> _parser = new pb::MessageParser<MissionConfig>(() => new MissionConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionConfig(MissionConfig other) : this() {
      treatmentDuration_ = other.treatmentDuration_;
      routes_ = other.routes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionConfig Clone() {
      return new MissionConfig(this);
    }

    /// <summary>Field number for the "treatment_duration" field.</summary>
    public const int TreatmentDurationFieldNumber = 1;
    private int treatmentDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TreatmentDuration {
      get { return treatmentDuration_; }
      set {
        treatmentDuration_ = value;
      }
    }

    /// <summary>Field number for the "routes" field.</summary>
    public const int RoutesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Pbdrone.MissionRoute> _repeated_routes_codec
        = pb::FieldCodec.ForMessage(50, global::Pbdrone.MissionRoute.Parser);
    private readonly pbc::RepeatedField<global::Pbdrone.MissionRoute> routes_ = new pbc::RepeatedField<global::Pbdrone.MissionRoute>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Pbdrone.MissionRoute> Routes {
      get { return routes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TreatmentDuration != other.TreatmentDuration) return false;
      if(!routes_.Equals(other.routes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TreatmentDuration != 0) hash ^= TreatmentDuration.GetHashCode();
      hash ^= routes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TreatmentDuration != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TreatmentDuration);
      }
      routes_.WriteTo(output, _repeated_routes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TreatmentDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TreatmentDuration);
      }
      size += routes_.CalculateSize(_repeated_routes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionConfig other) {
      if (other == null) {
        return;
      }
      if (other.TreatmentDuration != 0) {
        TreatmentDuration = other.TreatmentDuration;
      }
      routes_.Add(other.routes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TreatmentDuration = input.ReadInt32();
            break;
          }
          case 50: {
            routes_.AddEntriesFrom(input, _repeated_routes_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 9
  /// </summary>
  public sealed partial class CommandResponse : pb::IMessage<CommandResponse> {
    private static readonly pb::MessageParser<CommandResponse> _parser = new pb::MessageParser<CommandResponse>(() => new CommandResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommandResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandResponse(CommandResponse other) : this() {
      command_ = other.command_;
      successful_ = other.successful_;
      response_ = other.response_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandResponse Clone() {
      return new CommandResponse(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private string command_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Command {
      get { return command_; }
      set {
        command_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "successful" field.</summary>
    public const int SuccessfulFieldNumber = 2;
    private bool successful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Successful {
      get { return successful_; }
      set {
        successful_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 3;
    private string response_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Response {
      get { return response_; }
      set {
        response_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommandResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommandResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      if (Successful != other.Successful) return false;
      if (Response != other.Response) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Command.Length != 0) hash ^= Command.GetHashCode();
      if (Successful != false) hash ^= Successful.GetHashCode();
      if (Response.Length != 0) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Command.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Command);
      }
      if (Successful != false) {
        output.WriteRawTag(16);
        output.WriteBool(Successful);
      }
      if (Response.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Command.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Command);
      }
      if (Successful != false) {
        size += 1 + 1;
      }
      if (Response.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommandResponse other) {
      if (other == null) {
        return;
      }
      if (other.Command.Length != 0) {
        Command = other.Command;
      }
      if (other.Successful != false) {
        Successful = other.Successful;
      }
      if (other.Response.Length != 0) {
        Response = other.Response;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Command = input.ReadString();
            break;
          }
          case 16: {
            Successful = input.ReadBool();
            break;
          }
          case 26: {
            Response = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 10
  /// </summary>
  public sealed partial class AreaResult : pb::IMessage<AreaResult> {
    private static readonly pb::MessageParser<AreaResult> _parser = new pb::MessageParser<AreaResult>(() => new AreaResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AreaResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AreaResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AreaResult(AreaResult other) : this() {
      areaID_ = other.areaID_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AreaResult Clone() {
      return new AreaResult(this);
    }

    /// <summary>Field number for the "areaID" field.</summary>
    public const int AreaIDFieldNumber = 1;
    private int areaID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AreaID {
      get { return areaID_; }
      set {
        areaID_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Pbdrone.AreaResult.Types.Status status_ = global::Pbdrone.AreaResult.Types.Status.NotStarted;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.AreaResult.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AreaResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AreaResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AreaID != other.AreaID) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AreaID != 0) hash ^= AreaID.GetHashCode();
      if (Status != global::Pbdrone.AreaResult.Types.Status.NotStarted) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AreaID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AreaID);
      }
      if (Status != global::Pbdrone.AreaResult.Types.Status.NotStarted) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AreaID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AreaID);
      }
      if (Status != global::Pbdrone.AreaResult.Types.Status.NotStarted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AreaResult other) {
      if (other == null) {
        return;
      }
      if (other.AreaID != 0) {
        AreaID = other.AreaID;
      }
      if (other.Status != global::Pbdrone.AreaResult.Types.Status.NotStarted) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AreaID = input.ReadInt32();
            break;
          }
          case 16: {
            Status = (global::Pbdrone.AreaResult.Types.Status) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AreaResult message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("NOT_STARTED")] NotStarted = 0,
        [pbr::OriginalName("IN_PROGRESS")] InProgress = 1,
        [pbr::OriginalName("FINISHED")] Finished = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// Code 11
  /// </summary>
  public sealed partial class Configuration : pb::IMessage<Configuration> {
    private static readonly pb::MessageParser<Configuration> _parser = new pb::MessageParser<Configuration>(() => new Configuration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Configuration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Configuration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Configuration(Configuration other) : this() {
      list_ = other.list_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Configuration Clone() {
      return new Configuration(this);
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Pbdrone.ConfigEntry> _repeated_list_codec
        = pb::FieldCodec.ForMessage(10, global::Pbdrone.ConfigEntry.Parser);
    private readonly pbc::RepeatedField<global::Pbdrone.ConfigEntry> list_ = new pbc::RepeatedField<global::Pbdrone.ConfigEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Pbdrone.ConfigEntry> List {
      get { return list_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Configuration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Configuration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!list_.Equals(other.list_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= list_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      list_.WriteTo(output, _repeated_list_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += list_.CalculateSize(_repeated_list_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Configuration other) {
      if (other == null) {
        return;
      }
      list_.Add(other.list_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 12
  /// </summary>
  public sealed partial class ConfigEntry : pb::IMessage<ConfigEntry> {
    private static readonly pb::MessageParser<ConfigEntry> _parser = new pb::MessageParser<ConfigEntry>(() => new ConfigEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEntry(ConfigEntry other) : this() {
      section_ = other.section_;
      option_ = other.option_;
      value_ = other.value_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigEntry Clone() {
      return new ConfigEntry(this);
    }

    /// <summary>Field number for the "section" field.</summary>
    public const int SectionFieldNumber = 1;
    private string section_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Section {
      get { return section_; }
      set {
        section_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "option" field.</summary>
    public const int OptionFieldNumber = 2;
    private string option_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Option {
      get { return option_; }
      set {
        option_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 4;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Section != other.Section) return false;
      if (Option != other.Option) return false;
      if (Value != other.Value) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Section.Length != 0) hash ^= Section.GetHashCode();
      if (Option.Length != 0) hash ^= Option.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Section.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Section);
      }
      if (Option.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Option);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Value);
      }
      if (Id != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Section.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Section);
      }
      if (Option.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Option);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigEntry other) {
      if (other == null) {
        return;
      }
      if (other.Section.Length != 0) {
        Section = other.Section;
      }
      if (other.Option.Length != 0) {
        Option = other.Option;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Section = input.ReadString();
            break;
          }
          case 18: {
            Option = input.ReadString();
            break;
          }
          case 26: {
            Value = input.ReadString();
            break;
          }
          case 32: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Code 13
  /// </summary>
  public sealed partial class MissionRoute : pb::IMessage<MissionRoute> {
    private static readonly pb::MessageParser<MissionRoute> _parser = new pb::MessageParser<MissionRoute>(() => new MissionRoute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionRoute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pbdrone.MessagesReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionRoute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionRoute(MissionRoute other) : this() {
      routeID_ = other.routeID_;
      status_ = other.status_;
      flyThrough_ = other.flyThrough_;
      lastEntryModification_ = other.lastEntryModification_;
      lastAreaModification_ = other.lastAreaModification_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionRoute Clone() {
      return new MissionRoute(this);
    }

    /// <summary>Field number for the "routeID" field.</summary>
    public const int RouteIDFieldNumber = 1;
    private int routeID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RouteID {
      get { return routeID_; }
      set {
        routeID_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Pbdrone.MissionRoute.Types.Status status_ = global::Pbdrone.MissionRoute.Types.Status.NotStarted;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pbdrone.MissionRoute.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "flyThrough" field.</summary>
    public const int FlyThroughFieldNumber = 3;
    private bool flyThrough_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool FlyThrough {
      get { return flyThrough_; }
      set {
        flyThrough_ = value;
      }
    }

    /// <summary>Field number for the "lastEntryModification" field.</summary>
    public const int LastEntryModificationFieldNumber = 4;
    private long lastEntryModification_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LastEntryModification {
      get { return lastEntryModification_; }
      set {
        lastEntryModification_ = value;
      }
    }

    /// <summary>Field number for the "lastAreaModification" field.</summary>
    public const int LastAreaModificationFieldNumber = 5;
    private long lastAreaModification_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LastAreaModification {
      get { return lastAreaModification_; }
      set {
        lastAreaModification_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionRoute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionRoute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RouteID != other.RouteID) return false;
      if (Status != other.Status) return false;
      if (FlyThrough != other.FlyThrough) return false;
      if (LastEntryModification != other.LastEntryModification) return false;
      if (LastAreaModification != other.LastAreaModification) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RouteID != 0) hash ^= RouteID.GetHashCode();
      if (Status != global::Pbdrone.MissionRoute.Types.Status.NotStarted) hash ^= Status.GetHashCode();
      if (FlyThrough != false) hash ^= FlyThrough.GetHashCode();
      if (LastEntryModification != 0L) hash ^= LastEntryModification.GetHashCode();
      if (LastAreaModification != 0L) hash ^= LastAreaModification.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RouteID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RouteID);
      }
      if (Status != global::Pbdrone.MissionRoute.Types.Status.NotStarted) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (FlyThrough != false) {
        output.WriteRawTag(24);
        output.WriteBool(FlyThrough);
      }
      if (LastEntryModification != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(LastEntryModification);
      }
      if (LastAreaModification != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(LastAreaModification);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RouteID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RouteID);
      }
      if (Status != global::Pbdrone.MissionRoute.Types.Status.NotStarted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (FlyThrough != false) {
        size += 1 + 1;
      }
      if (LastEntryModification != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastEntryModification);
      }
      if (LastAreaModification != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastAreaModification);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionRoute other) {
      if (other == null) {
        return;
      }
      if (other.RouteID != 0) {
        RouteID = other.RouteID;
      }
      if (other.Status != global::Pbdrone.MissionRoute.Types.Status.NotStarted) {
        Status = other.Status;
      }
      if (other.FlyThrough != false) {
        FlyThrough = other.FlyThrough;
      }
      if (other.LastEntryModification != 0L) {
        LastEntryModification = other.LastEntryModification;
      }
      if (other.LastAreaModification != 0L) {
        LastAreaModification = other.LastAreaModification;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RouteID = input.ReadInt32();
            break;
          }
          case 16: {
            Status = (global::Pbdrone.MissionRoute.Types.Status) input.ReadEnum();
            break;
          }
          case 24: {
            FlyThrough = input.ReadBool();
            break;
          }
          case 32: {
            LastEntryModification = input.ReadInt64();
            break;
          }
          case 40: {
            LastAreaModification = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the MissionRoute message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("NOT_STARTED")] NotStarted = 0,
        [pbr::OriginalName("IN_PROGRESS")] InProgress = 1,
        [pbr::OriginalName("FINISHED")] Finished = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
